version: '3'

services:

  postgres:
    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    env_file:
      - .local-env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: