# Generated by Django 3.0.3 on 2020-03-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('kind', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('SNAKE', 'Snake'), ('SPIDER', 'Spider'), ('TURTLE', 'Turtle')], max_length=20)),
            ],
        ),
    ]
