- name: Add singing key from postgres repo
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Get version of ubuntu
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add postgres APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_version.stdout }}-pgdg main"
    state: present
  become: yes

- name: Install postgres
  apt:
    name: postgresql-12
    state: present
  become: yes

- name: Start and enable postgres
  service:
    name: postgresql
    enabled: yes
    state: started
  become: yes

- name: Create database
  postgresql_db:
    name: "{{ app_name }}"
  become_user: postgres
  become: yes

- name: Configure a new postgresql user
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER
  become: yes
  become_user: postgres
  notify:
    - restart postgres
